[default]
via_ir = false
out = 'out'
libs = ["lib"]
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
    'forge-std/=lib/forge-std/src/',
]
optimizer_runs = 200

[optimized]
solc = '0.8.10'
